name: pixelstrict
description: Deterministic strict pixel art reconstruction.
publish_to: none
version: 0.1.9+10
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.8.4
  file_picker: ^13.1.0
  hooks: ^2.2.0
  native_toolchain_rust: ^1.0.7
  code_assets: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/branding/pixelstrict-mark.png
